# Generated by Django 3.1.1 on 2023-04-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='dummy_field',
            field=models.IntegerField(default=0),
        ),
    ]
